version: "2"

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused

linters-settings:
  lll:
    line-length: 140

issues:
  exclude-use-default: false
