version: "2"

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    lll:
      line-length: 140
